# Generated by Django 2.2.4 on 2020-04-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('checkstate', models.BooleanField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '水果',
                'verbose_name_plural': '水果',
            },
        ),
    ]
